### ISSUE TITLE
Submit/deploy as Edge extension

### ISSUE THREAD

**Issue by filoxo** [single-spa/single-spa-inspector#42]
Now that Edge is Chromium-based, we should be able to submit the Chrome build almost as-is, just with a modification to descriptions in the manifest files ([I saw a Preact core team member report that this is possible, on Twitter](https://twitter.com/marvinhagemeist/status/1223672114273800192?s=20)). Might also investigate if we can add it as a build target in wext/shipit.

**Comment by filoxo** [comment]
I created https://github.com/LinusU/wext-shipit/issues/15 on the wext/shipit repo.

**Comment by frehner** [comment]
Oh I thought edge extensions were just downloaded from the chrome extension store.

**Comment by filoxo** [comment]
Closing as there still isn't a programmatic api to allow for automated deployments as of today, as well as single-spa-inspector is pretty stagnant at this point.
