### ISSUE TITLE
Overlays are no longer colored by a generated value from their names

### ISSUE THREAD

**Issue by TheMcMurder** [single-spa/single-spa-inspector#44]
From: https://single-spa.js.org/docs/devtools

>       color: "#000", // the default for this is actually based on the app's name, so it's dynamic. can be a hex or a CSS color name
      background: "#000", // the default for this is actually based on the app's name, so it's dynamic. can be a hex or a CSS color name

These seem to always be black here: https://react.microfrontends.app/people

**Comment by filoxo** [comment]
I'm taking a look at this today. I'm testing just `getColorFromString` (https://github.com/single-spa/single-spa-inspector/blob/236ba825994a5010d21c17dd92c30146f5c97cdb/src/inspected-window-helpers/overlay-helpers.js#L132) and it works correctly _except_ if the app name contains a `@`. Whenever that character is present, it returns that black color.
