### ISSUE TITLE
Not showing utility mfe or root-config (SystemJS modules that are not single-spa apps)

### ISSUE THREAD

**Issue by TheMcMurder** [single-spa/single-spa-inspector#45]
Currently the inspector only shows registered applications and it doesn't show any other mfe types.

This introduces a weird disconnect where this tool doesn't work great with the recommended approach. Import-map-overrides has features this doesn't have that directly relate to a single-spa application.

**Comment by filoxo** [comment]
Not showing those makes sense though, they're not single-spa applications so [`getRawAppData`](https://github.com/single-spa/single-spa/blob/6f2a09e7785e1b0095ae5646cfeb8f4acdbfe02f/src/applications/apps.js#L37) can't include them.

I do agree though, maybe we can instead reimplement the functionality to find all importmap module and allow overriding them from within this extension. Maybe as a separate tab? Like what the newest version of the React Devtools have done.

**Comment by TheMcMurder** [comment]
That's sort of what I was thinking. Leave the existing behavior as is but add a new tab that could function as an optional replacement for the import-map-overrides tool for people who want it.
