### ISSUE TITLE
Temporary disable an override

### ISSUE THREAD

**Issue by BartJanvanAssen** [single-spa/single-spa-inspector#48]
Since working for quite some time with the inspector, its very powerful!
Can we further improve it by add a toggle that can temporary disable an override? This would help a lot 👍 

![image](https://user-images.githubusercontent.com/4742816/83928959-dc84ab00-a791-11ea-8944-e14381fe0e91.png)

**Comment by joeldenning** [comment]
single-spa-inspector uses import-map-overrides for this, and import map overrides has the ability to disable overrides through the [`disableOverride` function](https://github.com/joeldenning/import-map-overrides/blob/master/docs/api.md#disableoverride).

This could be implemented by calling that function.
