### ISSUE TITLE
Inspector display no table rows

### ISSUE THREAD

**Issue by werts** [single-spa/single-spa-inspector#53]
there is no table rows displayed in the inspector.
I have tested imports-map-override like the below:
`html

<import-map-overrides-full
  show-when-local-storage="devtools"
></import-map-overrides-full>
`
it  works well, but the single-spa-inpector always displays empty rows,it seems that no apps to display.

**Comment by filoxo** [comment]
Single-spa-inspector does not interop with import-map-overrides, though there's been some desire to implement that (see https://github.com/single-spa/single-spa-inspector/issues/45, #48, #52). Closing since this isn't even a feature that single-spa-inspector currently has.

**Comment by werts** [comment]
Maybe i did not demonstrate clearly, all features listed in the docs[https://single-spa.js.org/docs/devtools](https://single-spa.js.org/docs/devtools) i cant get. for example, because  there is no table rows displayed,where can i get all registered applications?  and the same as statuses ?

**Comment by filoxo** [comment]
Oh I see, interesting. One thing that trips people up is that Parcels do not show up in the UI. Are your applications implemented as Parcels instead of using the registerApplication api?

**Comment by werts** [comment]
Aha, i'm using registerApplication api , one strange thing is that using import-map-override can detects all apps, but the inspector keeps empty always, i also atempt to find if there is some errors occur, but got nothing
