### ISSUE TITLE
Parcels don't show up in the list.

### ISSUE THREAD

**Issue by chrisbrooks** [single-spa/single-spa-inspector#57]
Can't seem to see parcels in the list but when I do the devtools config I can see them in the UI with overlays on.

**Comment by joeldenning** [comment]
It's expected that parcels are not in the list - it was never implemented.

I'm open to it being added, but it would require some changes to single-spa, as currently there are no APIs for retrieving all of the mounted parcels.

**Comment by chrisbrooks** [comment]
This would be super helpful and on that note as you just said @joeldenning it would be nice to check if a parcel has been mounted in the same way with registered applications you can check.

**Comment by joeldenning** [comment]
I don't think I'll get to this anytime soon, but am happy to review a pull request for it, and guide on what an implementation would look like

**Comment by danielbonatto** [comment]
+1

**Comment by pmjhonwang** [comment]
https://github.com/joeldenning/import-map-overrides 
these work fine for me
@chrisbrooks
