### ISSUE TITLE
extention not working for chrome

### ISSUE THREAD

**Issue by pmjhonwang** [single-spa/single-spa-inspector#61]
Uncaught (in promise) Error: eval Cmd 'window.__SINGLE_SPA_DEVTOOLS__.exposed Methods.getRawAppData()' failed: {"code":"E_PROTOCOLERROR","description":"Inspector protocol error: %s","details":["Object reference chain is too long"],"isError":true}

Google Chrome
Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by pmjhonwang** [comment]
```typescript
import singleSpa from "single-spa";
import { BehaviorSubject } from 'rxjs'

const customProps = {
    ...,
     subject: new BehavioSubject("defaultValue")
}

singleSpa.registerApplication({
  name: app,
  app: () => System.import(app),
  activeWhen,
  customProps,
});
```

**Comment by joeldenning** [comment]
I am using Chrome Version 90.0.4430.212 (Official Build) (x86_64), and do not see the error.
