### ISSUE TITLE
Inspector bug report

### ISSUE THREAD

**Issue by IsabelGraciano** [single-spa/single-spa-inspector#92]
Error during addOverride. evalCmd '(function() {
        return window.importMapOverrides.addOverride("quality-interaction-analysis", "https://localhost:3001/js/spa.js")
      })()' failed: {"isException":true,"value":"TypeError: Cannot read properties of undefined (reading 'addOverride')\n    at <anonymous>:2:42\n    at <anonymous>:3:9"}

```
Error: evalCmd '(function() {
        return window.importMapOverrides.addOverride("quality-interaction-analysis", "https://localhost:3001/js/spa.js")
      })()' failed: {"isException":true,"value":"TypeError: Cannot read properties of undefined (reading 'addOverride')\n    at <anonymous>:2:42\n    at <anonymous>:3:9"}
    at c (chrome-extension://emldbibkihanfiaiaghebffnbahjcgcp/build/panelApp.js:31:9214)
    at async chrome-extension://emldbibkihanfiaiaghebffnbahjcgcp/build/panelApp.js:31:11758
    at async Promise.all (index 0)
    at async commitOverrides (chrome-extension://emldbibkihanfiaiaghebffnbahjcgcp/build/panelApp.js:31:12135)```

**Comment by joeldenning** [comment]
This looks like the import-map-overrides library hasn't been loaded into the web page. Originally, single-spa-inspector worked without import-map-overrides, but then some former maintainers decided it was in conflict with import-map-overrides and feuded over whether to archive single-spa-inspector or not.
